version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/java:21
    volumes:
      - .:/workspace
    command: sleep infinity
    ports:
      - "8080:8080"   # Spring Boot
      - "5173:5173"   # Vue
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: master_db
      TZ: Asia/Shanghai
    ports:
      - "3308:3306"  # 宿主机访问3308，容器内部仍是3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
