server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
#    url: jdbc:mysql://localhost:3308/master_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://mysql:3306/master_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
#   url: jdbc:mysql://localhost:3308/master_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.work.entity
  configuration:
    databaseId: mysql
    map-underscore-to-camel-case: true

jwt:
  merchant-secret: your_merchant_secret_32_chars_or_more
  admin-secret: your_admin_secret_32_chars_or_more
  expire: 8640000000          # 1 天（秒）
  header: Authorization
